#!/bin/sh

set -e

if [ -t 1 ]; then
  BLUE='\033[0;34m'
  YELLOW='\033[0;33m'
  GREEN='\033[0;32m'
  BOLD='\033[1m'
  NC='\033[0m'
else
  BLUE=''
  YELLOW=''
  GREEN=''
  BOLD=''
  NC=''
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
CERT_DIR="$ROOT_DIR/certs"
CERT_SCRIPT="$ROOT_DIR/scripts/certs/dev-certs.sh"

APP_ENV="${1:-${APP_ENV:-development}}"

NGINX_ENV="$ROOT_DIR/containers/nginx/.env.$APP_ENV"
BACKEND_ENV="$ROOT_DIR/containers/backend/docker/.env.$APP_ENV"
SOCKET_ENV="$ROOT_DIR/containers/socket/docker/.env.$APP_ENV"
FRONTEND_ENV="$ROOT_DIR/containers/frontend/docker/.env.$APP_ENV"
DB_ENV="$ROOT_DIR/containers/database/docker/.env.$APP_ENV"
CLOUDFLARED_ENV="$ROOT_DIR/containers/cloudflared/.env.$APP_ENV"

section() {
  printf "\n${BLUE}%s${NC}\n" "$1"
}

info() {
  printf "${BOLD}->${NC} %s\n" "$1"
}

success() {
  printf "${GREEN}OK${NC} %s\n" "$1"
}

warn() {
  printf "${YELLOW}WARN${NC} %s\n" "$1"
}

ensure_file() {
  file="$1"

  if [ ! -f "$file" ]; then
    mkdir -p "$(dirname "$file")"
    touch "$file"
    success "Created missing file: $file"
  fi
}

append_if_missing() {
  file="$1"
  key="$2"
  default="$3"

  touch "$file"

  if ! grep -q "^${key}=" "$file"; then
    warn "Missing variable $key in $(basename "$file")"

    printf "%s [%s]: " "$key" "$default"
    read -r input

    value="${input:-$default}"

    echo "${key}=${value}" >> "$file"
    success "Added $key to $(basename "$file")"
  fi
}

get_env_value() {
  file="$1"
  key="$2"

  if [ ! -f "$file" ]; then
    return 0
  fi

  grep -E "^${key}=" "$file" | tail -n 1 | cut -d '=' -f 2-
}

set_env_var() {
  file="$1"
  key="$2"
  value="$3"

  sed -i.bak "/^${key}=/d" "$file"
  echo "${key}=${value}" >> "$file"
}

extract_url_scheme() {
  url="$1"
  printf '%s' "$url" | sed -E 's#^([a-zA-Z][a-zA-Z0-9+.-]*)://.*#\1#'
}

extract_url_authority() {
  url="$1"
  printf '%s' "$url" | sed -E 's#^[a-zA-Z][a-zA-Z0-9+.-]*://([^/]+).*$#\1#'
}

extract_url_host() {
  authority="$(extract_url_authority "$1")"
  printf '%s' "${authority%%:*}"
}

extract_url_port() {
  authority="$(extract_url_authority "$1")"

  case "$authority" in
    *:*)
      printf '%s' "${authority##*:}"
      ;;
    *)
      printf ''
      ;;
  esac
}

is_ipv4_address() {
  host="$1"
  printf '%s' "$host" | grep -Eq '^[0-9]{1,3}(\.[0-9]{1,3}){3}$'
}

get_google_callback_base_url() {
  public_url="$1"
  host="$(extract_url_host "$public_url")"

  if ! is_ipv4_address "$host"; then
    printf '%s' "$public_url"
    return 0
  fi

  scheme="$(extract_url_scheme "$public_url")"
  port="$(extract_url_port "$public_url")"

  if [ -n "$port" ]; then
    printf '%s://localhost:%s' "$scheme" "$port"
  else
    printf '%s://localhost' "$scheme"
  fi
}

echo
printf "${BOLD}Environment setup${NC}\n"
info "Preparing generated env files for: $APP_ENV"
info "Project root: $ROOT_DIR"

section "Certificate check"

if [ ! -d "$CERT_DIR" ] || [ -z "$(ls -A "$CERT_DIR" 2>/dev/null)" ]; then
  warn "Development certificates were not found."
  info "Generating fresh certificates in $CERT_DIR"

  sh "$CERT_SCRIPT"

  success "Certificates generated."
else
  success "Using existing certificates from $CERT_DIR"
fi

ensure_file "$NGINX_ENV"
ensure_file "$BACKEND_ENV"
ensure_file "$SOCKET_ENV"
ensure_file "$DB_ENV"
ensure_file "$FRONTEND_ENV"
ensure_file "$CLOUDFLARED_ENV"

section "Generated files"

cat > "$NGINX_ENV" <<EOF
# Auto-generated by setup-env.sh for $APP_ENV
# Do not commit this file

CERT_DIR=$CERT_DIR

EOF

success "Wrote nginx env file"

section "Database configuration"

sync_db_vars_if_needed() {
  backend_user="$(get_env_value "$BACKEND_ENV" "PGUSER")"
  backend_password="$(get_env_value "$BACKEND_ENV" "PGPASSWORD")"
  backend_db="$(get_env_value "$BACKEND_ENV" "PGDATABASE")"

  db_user="$(get_env_value "$DB_ENV" "POSTGRES_USER")"
  db_password="$(get_env_value "$DB_ENV" "POSTGRES_PASSWORD")"
  db_name="$(get_env_value "$DB_ENV" "POSTGRES_DB")"

  needs_prompt=0

  [ -z "$backend_user" ] && needs_prompt=1
  [ -z "$backend_password" ] && needs_prompt=1
  [ -z "$backend_db" ] && needs_prompt=1

  [ -z "$db_user" ] && needs_prompt=1
  [ -z "$db_password" ] && needs_prompt=1
  [ -z "$db_name" ] && needs_prompt=1

  [ "$backend_user" != "$db_user" ] && needs_prompt=1
  [ "$backend_password" != "$db_password" ] && needs_prompt=1
  [ "$backend_db" != "$db_name" ] && needs_prompt=1

  if [ "$needs_prompt" -eq 0 ]; then
    success "Database variables already exist and match."
    return 0
  fi

  warn "Database variables are missing or out of sync."
  info "We will align backend and database credentials now."

  default_user="${backend_user:-${db_user:-app}}"
  default_password="${backend_password:-${db_password:-change-me}}"
  _default_db_name="$([ "$APP_ENV" = "development" ] && echo "app_development" || echo "app")"
  default_db="${backend_db:-${db_name:-$_default_db_name}}"

  printf "Postgres user [%s]: " "$default_user"
  read -r input_user
  DB_USER="${input_user:-$default_user}"

  printf "Postgres password [%s]: " "$default_password"
  read -r input_password
  DB_PASSWORD="${input_password:-$default_password}"

  printf "Database name [%s]: " "$default_db"
  read -r input_db
  DB_NAME="${input_db:-$default_db}"

  set_env_var "$BACKEND_ENV" "PGUSER" "$DB_USER"
  set_env_var "$BACKEND_ENV" "PGPASSWORD" "$DB_PASSWORD"
  set_env_var "$BACKEND_ENV" "PGDATABASE" "$DB_NAME"
  set_env_var "$BACKEND_ENV" "PGHOST" "postgres"

  set_env_var "$DB_ENV" "POSTGRES_USER" "$DB_USER"
  set_env_var "$DB_ENV" "POSTGRES_PASSWORD" "$DB_PASSWORD"
  set_env_var "$DB_ENV" "POSTGRES_DB" "$DB_NAME"

  success "Database variables synchronized."
}

sync_db_vars_if_needed

section "Backend secrets"

current_session_secret="$(get_env_value "$BACKEND_ENV" "SESSION_SECRET")"
if [ -z "$current_session_secret" ]; then
  SESSION_SECRET=$(openssl rand -hex 32)
  set_env_var "$BACKEND_ENV" "SESSION_SECRET" "$SESSION_SECRET"
  success "Generated SESSION_SECRET"
else
  success "Reused existing SESSION_SECRET"
fi

current_public_api_key="$(get_env_value "$BACKEND_ENV" "PUBLIC_API_KEY")"
if [ -z "$current_public_api_key" ]; then
  PUBLIC_API_KEY=$(openssl rand -hex 32)
  set_env_var "$BACKEND_ENV" "PUBLIC_API_KEY" "$PUBLIC_API_KEY"
  success "Generated PUBLIC_API_KEY"
else
  success "Reused existing PUBLIC_API_KEY"
fi

set_env_var "$BACKEND_ENV" "SESSION_TTL" "604800000"
success "Set SESSION_TTL"

current_socket_secret="$(get_env_value "$BACKEND_ENV" "SOCKET_INTERNAL_SECRET")"
if [ -z "$current_socket_secret" ]; then
  current_socket_secret="$(get_env_value "$SOCKET_ENV" "SOCKET_INTERNAL_SECRET")"
fi

if [ -z "$current_socket_secret" ]; then
  SOCKET_INTERNAL_SECRET="$(openssl rand -hex 32)"
  current_socket_secret="$SOCKET_INTERNAL_SECRET"
  success "Generated SOCKET_INTERNAL_SECRET"
else
  success "Reused existing SOCKET_INTERNAL_SECRET"
fi

# Shared internal secret used by both backend and socket.
set_env_var "$BACKEND_ENV" "SOCKET_INTERNAL_SECRET" "$current_socket_secret"

section "Socket configuration"

cat > "$SOCKET_ENV" <<EOF
# Auto-generated by setup-env.sh for $APP_ENV
# Do not commit this file

SOCKET_INTERNAL_SECRET=$current_socket_secret

EOF

success "Wrote socket env file"

current_google="$(get_env_value "$BACKEND_ENV" "GOOGLE_CLIENT_ID")"
if [ -z "$current_google" ]; then
  section "Google OAuth"
  warn "Google OAuth values are still missing."
  info "Open https://console.cloud.google.com/ and create a Web application OAuth client."
  info "Use this redirect URI: https://your-public-app.example.com/api/auth/callback/google"
  info "It must match GOOGLE_CALLBACK_URL exactly."
  info "If APP_BASE_URL uses a local IP, this script will switch the callback host to localhost automatically."
fi

append_if_missing "$BACKEND_ENV" "GOOGLE_CLIENT_ID" "YOUR_GOOGLE_CLIENT_ID"
append_if_missing "$BACKEND_ENV" "GOOGLE_CLIENT_SECRET" "YOUR_GOOGLE_CLIENT_SECRET"
append_if_missing "$BACKEND_ENV" "GMAIL_REFRESH_TOKEN" "YOUR_GMAIL_REFRESH_TOKEN"
append_if_missing "$BACKEND_ENV" "GMAIL_SENDER_EMAIL" "YOUR_GMAIL_SENDER_EMAIL"
append_if_missing "$BACKEND_ENV" "GMAIL_SENDER_NAME" "YOUR_GMAIL_SENDER_NAME"
 

section "App URLs"

frontend_node_env="development"

if [ "$APP_ENV" != "development" ]; then
  frontend_node_env="production"
fi

if [ -n "${PUBLIC_APP_URL:-}" ]; then
  PUBLIC_APP_URL="${PUBLIC_APP_URL%/}"
else
  HOST='localhost'

  if command -v ip > /dev/null 2>&1; then
    detected_host=$(ip -4 route get 1.1.1.1 2> /dev/null | xargs | cut -d ' ' -f 7)
    if [ -n "$detected_host" ]; then
      HOST="$detected_host"
    fi
  fi

  if [ "$HOST" = 'localhost' ] && command -v ifconfig > /dev/null 2>&1; then
    detected_host=$(ifconfig en0 | sed '5q;d' | xargs | cut -d ' ' -f 2 | cut -d '/' -f 1)
    if [ -n "$detected_host" ]; then
      HOST="$detected_host"
    fi
  fi

  key='host computer'
  default="$HOST"

  info "Detected host candidate: $default"
  printf "%s [%s]: " "$key" "$default"
  read -r input

  HOST="${input:-$default}"

  public_key='public app url'
  public_default="https://${HOST}:8443"

  printf "%s [%s]: " "$public_key" "$public_default"
  read -r input
  PUBLIC_APP_URL="${input:-$public_default}"
  PUBLIC_APP_URL="${PUBLIC_APP_URL%/}"
fi

set_env_var "$BACKEND_ENV" "APP_BASE_URL" "$PUBLIC_APP_URL"
GOOGLE_CALLBACK_BASE_URL="$(get_google_callback_base_url "$PUBLIC_APP_URL")"
set_env_var "$BACKEND_ENV" "GOOGLE_CALLBACK_URL" "$GOOGLE_CALLBACK_BASE_URL/api/auth/callback/google"
success "Set APP_BASE_URL to $PUBLIC_APP_URL"
success "Set GOOGLE_CALLBACK_URL to $GOOGLE_CALLBACK_BASE_URL/api/auth/callback/google"

section "Frontend configuration"

cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by setup-env.sh for $APP_ENV
# Do not commit this file

PORT=3000
HOSTNAME=0.0.0.0
HTTPS_KEY_PATH=/certs/localhost.key
HTTPS_CERT_PATH=/certs/localhost.crt

NODE_ENV=$frontend_node_env
API_BASE_URL=https://backend:4000

NEXT_PUBLIC_APP_URL=$PUBLIC_APP_URL
NEXT_PUBLIC_API_BASE_URL=/api
NEXT_PUBLIC_SOCKET_URL=$PUBLIC_APP_URL
NEXT_PUBLIC_LOCALE_COOKIE_NAME=locale

EOF

set_env_var "$SOCKET_ENV" "SOCKET_CORS_ORIGINS" "$PUBLIC_APP_URL"

success "Wrote frontend env file"
success "Updated socket CORS origin"

section "Summary"
success "Environment setup complete for $APP_ENV"
info "Generated files:"
info "  - $NGINX_ENV"
info "  - $BACKEND_ENV"
info "  - $SOCKET_ENV"
info "  - $FRONTEND_ENV"
info "  - $DB_ENV"
info "  - $CLOUDFLARED_ENV"
info "Public app URL: $PUBLIC_APP_URL"
info "Google callback URL: $GOOGLE_CALLBACK_BASE_URL/api/auth/callback/google"
echo
