#!/bin/sh

set -e

YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
CERT_DIR="$ROOT_DIR/certs"
CERT_SCRIPT="$ROOT_DIR/scripts/certs/dev-certs.sh"

APP_ENV="${1:-${APP_ENV:-development}}"

NGINX_ENV="$ROOT_DIR/containers/nginx/.env.$APP_ENV"
BACKEND_ENV="$ROOT_DIR/containers/backend/docker/.env.$APP_ENV"
FRONTEND_ENV="$ROOT_DIR/containers/frontend/docker/.env.$APP_ENV"
DB_ENV="$ROOT_DIR/containers/database/docker/.env.$APP_ENV"

ensure_file() {
  file="$1"

  if [ ! -f "$file" ]; then
    mkdir -p "$(dirname "$file")"
    touch "$file"
    echo "✅ Created missing file: $file"
  fi
}

append_if_missing() {
  file="$1"
  key="$2"
  default="$3"

  touch "$file"

  if ! grep -q "^${key}=" "$file"; then
    printf "${YELLOW}Missing variable %s in %s${NC}\n" "$key" "$(basename "$file")"

    printf "%s [%s]: " "$key" "$default"
    read -r input

    value="${input:-$default}"

    echo "${key}=${value}" >> "$file"
    printf "${GREEN}Added %s${NC}\n" "$key"
  fi
}

get_env_value() {
  file="$1"
  key="$2"

  if [ ! -f "$file" ]; then
    return 0
  fi

  grep -E "^${key}=" "$file" | tail -n 1 | cut -d '=' -f 2-
}

set_env_var() {
  file="$1"
  key="$2"
  value="$3"

  sed -i.bak "/^${key}=/d" "$file"
  echo "${key}=${value}" >> "$file"
}

echo
echo "🔧 Setting up $APP_ENV environment..."
echo

# -----------------------------
# Certificate Check
# -----------------------------

if [ ! -d "$CERT_DIR" ] || [ -z "$(ls -A "$CERT_DIR" 2>/dev/null)" ]; then
  echo "⚠️  Development certificates not found."
  echo "➡️  Generating certificates..."
  echo

  sh "$CERT_SCRIPT"

  echo
  echo "✅ Certificates generated."
  echo
else
  echo "✅ Development certificates found."
  echo
fi

ensure_file "$NGINX_ENV"
ensure_file "$BACKEND_ENV"
ensure_file "$DB_ENV"
ensure_file "$FRONTEND_ENV"

echo

# -----------------------------
# Nginx env
# -----------------------------

cat > "$NGINX_ENV" <<EOF
# Auto-generated by setup-env.sh for $APP_ENV
# Do not commit this file

CERT_DIR=$CERT_DIR

EOF

echo "✅ Nginx env vars generated"

# -----------------------------
# Database credentials
# -----------------------------

sync_db_vars_if_needed() {
  backend_user="$(get_env_value "$BACKEND_ENV" "PGUSER")"
  backend_password="$(get_env_value "$BACKEND_ENV" "PGPASSWORD")"
  backend_db="$(get_env_value "$BACKEND_ENV" "PGDATABASE")"

  db_user="$(get_env_value "$DB_ENV" "POSTGRES_USER")"
  db_password="$(get_env_value "$DB_ENV" "POSTGRES_PASSWORD")"
  db_name="$(get_env_value "$DB_ENV" "POSTGRES_DB")"

  needs_prompt=0

  [ -z "$backend_user" ] && needs_prompt=1
  [ -z "$backend_password" ] && needs_prompt=1
  [ -z "$backend_db" ] && needs_prompt=1

  [ -z "$db_user" ] && needs_prompt=1
  [ -z "$db_password" ] && needs_prompt=1
  [ -z "$db_name" ] && needs_prompt=1

  [ "$backend_user" != "$db_user" ] && needs_prompt=1
  [ "$backend_password" != "$db_password" ] && needs_prompt=1
  [ "$backend_db" != "$db_name" ] && needs_prompt=1

  if [ "$needs_prompt" -eq 0 ]; then
    echo "✅ Database variables already exist and match."
    return 0
  fi

  echo "⚠️  Database variables are missing or do not match."
  echo

  default_user="${backend_user:-${db_user:-app}}"
  default_password="${backend_password:-${db_password:-change-me}}"
  default_db="${backend_db:-${db_name:-app}}"

  printf "Postgres user [%s]: " "$default_user"
  read -r input_user
  DB_USER="${input_user:-$default_user}"

  printf "Postgres password [%s]: " "$default_password"
  read -r input_password
  DB_PASSWORD="${input_password:-$default_password}"

  printf "Database name [%s]: " "$default_db"
  read -r input_db
  DB_NAME="${input_db:-$default_db}"

  set_env_var "$BACKEND_ENV" "PGUSER" "$DB_USER"
  set_env_var "$BACKEND_ENV" "PGPASSWORD" "$DB_PASSWORD"
  set_env_var "$BACKEND_ENV" "PGDATABASE" "$DB_NAME"
  set_env_var "$BACKEND_ENV" "PGHOST" "postgres"

  set_env_var "$DB_ENV" "POSTGRES_USER" "$DB_USER"
  set_env_var "$DB_ENV" "POSTGRES_PASSWORD" "$DB_PASSWORD"
  set_env_var "$DB_ENV" "POSTGRES_DB" "$DB_NAME"

  echo
  echo "✅ Database variables synchronized."
}

sync_db_vars_if_needed

# -----------------------------
# Backend env
# -----------------------------

current_session_secret="$(get_env_value "$BACKEND_ENV" "SESSION_SECRET")"
if [ -z "$current_session_secret" ]; then
  SESSION_SECRET=$(openssl rand -hex 32)
  set_env_var "$BACKEND_ENV" "SESSION_SECRET" "$SESSION_SECRET"
fi

set_env_var "$BACKEND_ENV" "SESSION_TTL" "604800000"

append_if_missing "$BACKEND_ENV" "SOCKET_INTERNAL_SECRET" ""

current_google="$(get_env_value "$BACKEND_ENV" "GOOGLE_CLIENT_ID")"
if [ -z "$current_google" ]; then
  echo
  echo "🔐 Google OAuth configuration required"
  echo
  echo "To obtain GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET:"
  echo
  echo "1. Go to: https://console.cloud.google.com/"
  echo "2. Create a new project (or select an existing one)."
  echo "3. Navigate to:"
  echo "   APIs & Services → Credentials"
  echo "4. Click:"
  echo "   Create Credentials → OAuth Client ID"
  echo "5. Choose application type:"
  echo "   Web application"
  echo
  echo "6. Add the following Authorized redirect URI:"
  echo
  echo "   https://localhost:8443/api/auth/callback/google"
  echo
  echo "7. After creating it, Google will provide:"
  echo
  echo "   GOOGLE_CLIENT_ID"
  echo "   GOOGLE_CLIENT_SECRET"
  echo
  echo "Paste those values when prompted below."
  echo
fi

append_if_missing "$BACKEND_ENV" "GOOGLE_CLIENT_ID" "YOUR_GOOGLE_CLIENT_ID"
append_if_missing "$BACKEND_ENV" "GOOGLE_CLIENT_SECRET" "YOUR_GOOGLE_CLIENT_SECRET"
append_if_missing "$BACKEND_ENV" "GMAIL_REFRESH_TOKEN" "YOUR_GMAIL_REFRESH_TOKEN"
append_if_missing "$BACKEND_ENV" "GMAIL_SENDER_EMAIL" "YOUR_GMAIL_SENDER_EMAIL"
append_if_missing "$BACKEND_ENV" "GMAIL_SENDER_NAME" "YOUR_GMAIL_SENDER_NAME"

set_env_var "$BACKEND_ENV" "GOOGLE_CALLBACK_URL" "https://localhost:8443/api/auth/callback/google"
set_env_var "$BACKEND_ENV" "APP_BASE_URL" "https://localhost:8443"

echo

# -----------------------------
# Frontend env
# -----------------------------

frontend_node_env="development"

if [ "$APP_ENV" != "development" ]; then
  frontend_node_env="production"
fi

cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by setup-env.sh for $APP_ENV
# Do not commit this file

PORT=3000
HOSTNAME=0.0.0.0
HTTPS_KEY_PATH=/certs/localhost.key
HTTPS_CERT_PATH=/certs/localhost.crt

NODE_ENV=$frontend_node_env
API_BASE_URL=https://backend:4000

NEXT_PUBLIC_APP_URL=https://localhost:8443
NEXT_PUBLIC_API_BASE_URL=/api
NEXT_PUBLIC_SOCKET_URL=https://localhost:8443
NEXT_PUBLIC_LOCALE_COOKIE_NAME=locale

EOF

echo "✅ Frontend env vars generated"

echo
echo "✅ Environment setup complete."
echo