// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "globalError": {
      "title": "Something went wrong",
      "tryAgain": "Try again",
      "unexpectedMessage": "An unexpected error occurred"
    }
  },
  "components": {
    "breadcrumb": {
      "edit": "Edit profile",
      "home": "Home",
      "me": "My Account",
      "reset-password": "Reset Password"
    },
    "footer": {
      "appName": "Transcendence",
      "copyright": "© {year} {appName}. All rights reserved",
      "github": "GitHub",
      "privacy": "Privacy Policy",
      "terms": "Terms of Service"
    },
    "localeSwitcher": {
      "ariaLabel": "Language",
      "ca": "CA",
      "en": "EN",
      "es": "ES"
    },
    "submitButton": {
      "pendingLabel": "Submitting..."
    },
    "textAreaField": {
      "characterCount": "{current} of {max} characters"
    }
  },
  "layouts": {
    "locale": {
      "metadata": {
        "description": "Play Transcendence, chat with friends, and manage your account in one place.",
        "title": "Transcendence"
      }
    }
  },
  "pages": {
    "home": {
      "subtitle": "If you can see this, routing + dev server work.",
      "title": "Hello from Next in Docker 👋"
    },
    "game": {
      "description": "Play the Transcendence game and manage your turns.",
      "metadata": {
        "description": "Play the Transcendence game and manage your turns.",
        "title": "Game"
      },
      "title": "Game"
    },
    "me": {
      "metadata": {
        "description": "View and manage your Transcendence account details.",
        "title": "My Account"
      },
      "subtitle": "Access your protected account data.",
      "title": "My Account"
    },
    "notFound": {
      "backToHome": "Back to Home",
      "description": "The page you're looking for doesn't exist.",
      "title": "Page not found"
    },
    "privacy": {
      "metadata": {
        "description": "Learn what data Transcendence collects, how it is used, and how it is protected.",
        "title": "Privacy Policy"
      },
      "contact": {
        "description": "If you have any questions about this policy or wish to exercise your rights, please contact the development team through our <link>GitHub repository</link>.",
        "title": "Contact"
      },
      "dataCollected": {
        "description": "When you use our platform, we may collect the following information:",
        "items": {
          "email": "Email address (used for account registration and authentication)",
          "technical": "Technical data (browser type, device information, and IP address for security purposes)",
          "usage": "Usage data (game history, scores, and interaction logs)",
          "username": "Username (chosen by you to identify yourself in the game)"
        },
        "title": "Data Collected"
      },
      "dataUsage": {
        "description": "The data we collect is used exclusively for the following purposes:",
        "items": {
          "account": "Account management and authentication",
          "communication": "Sending necessary communications related to your account",
          "gameplay": "Providing the game experience and social features",
          "improvement": "Improving and optimizing the platform"
        },
        "title": "How We Use Your Data"
      },
      "intro": "At Transcendence, we value your privacy. This policy describes what data we collect, how we use it, how we store it, and what rights you have regarding your personal information.",
      "lastUpdated": "Last updated: April 2026",
      "rights": {
        "description": "As a user, you have the following rights regarding your personal data:",
        "items": {
          "access": "Right to access your personal data",
          "deletion": "Right to request deletion of your data",
          "portability": "Right to data portability",
          "rectification": "Right to correct inaccurate data"
        },
        "title": "Your Rights"
      },
      "storage": {
        "description": "Your data is stored securely on our servers. We implement industry-standard security measures including encrypted connections (HTTPS), secure password hashing, and regular security audits. We retain your data only for as long as your account is active or as needed to provide you with our services.",
        "title": "Data Storage and Security"
      },
      "title": "Privacy Policy"
    },
    "terms": {
      "metadata": {
        "description": "Review the rules, responsibilities, and legal terms for using Transcendence.",
        "title": "Terms of Service"
      },
      "acceptance": {
        "description": "By creating an account or using our services, you agree to these conditions in their entirety. If you do not agree with any part of these Terms, you must refrain from using the platform.",
        "title": "Acceptance of Terms"
      },
      "conduct": {
        "description": "To maintain a fair, respectful, and fun environment, you agree not to:",
        "items": {
          "cheating": "Use cheats, automation software (bots), or hacks to gain an advantage.",
          "disruption": "Attempt to disrupt the integrity or security of our servers.",
          "harassment": "Harass, abuse, or engage in behavior that harms the community or other players."
        },
        "title": "User Conduct"
      },
      "contact": {
        "description": "If you have any questions or wish to exercise your rights, please contact the development team by opening an issue on our <link>GitHub repository</link>.",
        "title": "Contact Us"
      },
      "disclaimer": {
        "description": "Transcendence is an educational and community-driven project. Consequently, the service is provided as is and as available. We do not warrant that the service will be uninterrupted, timely, secure, or error-free.",
        "title": "Disclaimers"
      },
      "intro": "Welcome to Transcendence. Your use of this platform is subject to the following Terms of Service, which govern the relationship between you and the development team.",
      "ip": {
        "description": "All content, including game code, graphics, and trademarks, is the property of Transcendence. We grant you a limited, non-transferable license for personal, non-commercial use.",
        "title": "Intellectual Property"
      },
      "lastUpdated": "Last updated: April 2026",
      "law": {
        "description": "These Terms shall be governed by and construed in accordance with the laws applicable to digital services within the scope of this project's jurisdiction.",
        "title": "Governing Law"
      },
      "registration": {
        "description": "You are responsible for maintaining the confidentiality of your credentials and for all activities that occur under your account.",
        "items": {
          "accuracy": "You agree to provide accurate and complete information during registration.",
          "security": "You must notify us immediately of any unauthorized use of your account."
        },
        "title": "Account Registration"
      },
      "termination": {
        "description": "We reserve the right to suspend or terminate your account at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.",
        "title": "Termination"
      },
      "title": "Terms of Service"
    }
  },
  "features": {
    "auth": {
      "actions": {
        "continueWithGoogle": "Continue with Google",
        "login": "Log in",
        "logoutAriaLabel": "Log out",
        "resendEmail": "Resend email",
        "sendEmail": "Send email",
        "signup": "Create account"
      },
      "changePassword": {
        "description": "Enter your current password and choose a new one.",
        "submit": "Save changes",
        "success": "Password updated successfully.",
        "title": "Change password"
      },
      "fields": {
        "confirmPassword": {
          "label": "Confirm password",
          "placeholder": "Re-enter your password"
        },
        "currentPassword": {
          "label": "Current password",
          "placeholder": "Enter your current password"
        },
        "email": {
          "label": "Email",
          "placeholder": "name@example.com"
        },
        "identifier": {
          "description": "Use the email address or username you signed up with.",
          "label": "Email or username",
          "placeholder": "name@example.com or username"
        },
        "newPassword": {
          "description": "Min 8 characters long.",
          "label": "New password",
          "placeholder": "Enter your new password"
        },
        "password": {
          "description": "Min 8 characters long.",
          "label": "Password",
          "placeholder": "Enter your password"
        },
        "username": {
          "label": "Username",
          "placeholder": "your_username"
        }
      },
      "login": {
        "forgotPassword": "Forgot password?",
        "goToSignup": "Create one",
        "metadata": {
          "description": "Sign in to your Transcendence account to play, chat, and manage your profile.",
          "title": "Log in"
        },
        "noAccount": "Don’t have an account?",
        "submit": "Log in",
        "title": "Log in"
      },
      "messages": {
        "or": "OR",
        "success": "Email sent. Wait before trying again."
      },
      "recover": {
        "backToLogin": "Back to login",
        "checkInbox": "Check your inbox and follow the instructions to set a new password.",
        "checkSpam": "If you can't find it, check your spam folder. If it's not there either, try again later.",
        "metadata": {
          "description": "Request a password reset email to regain access to your Transcendence account.",
          "title": "Recover account"
        },
        "rememberedPassword": "Remembered your password?",
        "sent": "We've sent password reset instructions to the address you entered.",
        "title": "Check your email"
      },
      "reset": {
        "backToLogin": "Back to login",
        "description": "Enter your new password.",
        "metadata": {
          "description": "Set a new password for your Transcendence account.",
          "title": "Reset password"
        },
        "submit": "Save new password",
        "success": "Password updated successfully.",
        "title": "Reset password"
      },
      "signup": {
        "goToLogin": "Log in",
        "haveAccount": "Already have an account?",
        "metadata": {
          "description": "Create your Transcendence account to start playing and connecting with friends.",
          "title": "Create account"
        },
        "privacy": {
          "error": "You must accept the Privacy Policy to continue.",
          "label": "I have read and agree to the <link>Privacy Policy</link>"
        },
        "title": "Create account"
      },
      "verification": {
        "backToLogin": "Log In",
        "checkInbox": "Check your inbox and follow the instructions to activate your account.",
        "checkSpam": "If you can't find it, check your spam folder. If it's not there either, you can resend it.",
        "invalidOrExpired": "Verification link is invalid or expired.",
        "isConfirmed": "Already confirmed?",
        "metadata": {
          "description": "Confirm your email address to activate your Transcendence account.",
          "title": "Verify your email"
        },
        "missingToken": "Verification token is missing.",
        "recoverTitle": "Recover account",
        "resendDescription": "Enter the email address you used to create your account.",
        "resending": "Sending...",
        "resendTitle": "Resend verification email",
        "sent": "We've sent you an email to confirm your account.",
        "title": "Check your email",
        "verified": "Email verified. Redirecting to your profile...",
        "verifying": "Verifying your email..."
      }
    },
    "chat": {
      "hideChat": "Hide Chat",
      "messageAriaLabel": "Message",
      "showChat": "Show Chat"
    },
    "directMessages": {
      "metadata": {
        "description": "Open private conversations with your friends on Transcendence.",
        "title": "Direct messages"
      },
      "emptyState": "No conversations yet",
      "listTitle": "Messages",
      "openList": "Open messages list",
      "closeList": "Close messages list",
      "selectionTitle": "Select a conversation",
      "selectionBody": "Choose a friend from the list to open your messages.",
      "accessTitle": "Direct messages",
      "accessBody": {
        "authenticated": "This conversation is only available between accepted friends.",
        "unauthenticated": "You need to be signed in to open a private chat."
      },
      "backToHome": "Back to home",
      "presence": {
        "online": "● Online",
        "away": "● Away",
        "offline": "Offline"
      }
    },
    "game": {
      "endTurn": "End turn",
      "healthLabel": "HP",
      "resetPlan": "Reset plan"
    },
    "navigation": {
      "createAccount": "Create account",
      "game": "Game",
      "home": "Home",
      "messages": "Messages",
      "login": "Log in",
      "logout": "Logout",
      "mainAriaLabel": "Main navigation",
      "menu": "Menu",
      "profile": "Profile",
      "settings": "Settings",
      "ui": "UI"
    },
    "profile": {
      "actions": {
        "changePassword": "Change password",
        "deleteAccount": "Delete account",
        "editProfile": "Edit profile"
      },
      "bio": "Bio",
      "delete": {
        "body": "This action permanently deletes your account, removes your profile, and signs you out. This cannot be undone.",
        "cancel": "Cancel",
        "description": "This permanently deletes your account and signs you out.",
        "title": "Delete account?"
      },
      "edit": {
        "placeholder": "Tell other players a little about yourself",
        "submit": "Save changes",
        "title": "Edit profile"
      },
      "emptyBio": "No bio yet",
      "fail": "Could not load your profile.",
      "metadata": {
        "publicDescription": "View {username}'s public Transcendence profile."
      },
      "provider": "Provider",
      "userId": "User ID",
      "username": "Username"
    },
    "settings": {
      "dark": "Dark",
      "language": "Language",
      "light": "Light",
      "theme": "Theme"
    },
    "social": {
      "actions": {
        "accept": "Accept",
        "addFriend": "Add friend",
        "cancel": "Cancel",
        "cancelRequest": "Cancel Request",
        "inviteToGame": "Invite to Game",
        "message": "Message",
        "reject": "Reject",
        "unfriend": "Remove Friend"
      },
      "emptyStates": {
        "offline": "No friends offline",
        "online": "No friends online right now",
        "pending": "No sent requests pending",
        "request": "No pending friend requests",
        "search": "No users found"
      },
      "friends": {
        "offline": "Friends offline",
        "online": "Friends online",
        "title": "Friends"
      },
      "guest": {
        "body": "To find friends, see who's online and play games, you need an account.",
        "login": "Login",
        "noAccount": "Don't have an account?",
        "signup": "Create one",
        "title": "Connect with the community"
      },
      "requests": {
        "now": "now",
        "received": "Received",
        "sent": "Sent",
        "title": "Requests"
      },
      "searchLabel": "Search",
      "searchPlaceholder": "Search users",
      "title": "Social"
    }
  },
  "validation": {
    "FIELD_TOO_LONG": "Too long.",
    "FIELD_TOO_SHORT": "Too short.",
    "INVALID_EMAIL": "Enter a valid email address.",
    "INVALID_EMAIL_OR_USERNAME": "Enter a valid email address or username.",
    "INVALID_FORMAT": "Invalid format.",
    "INVALID_USERNAME": "Username must be 3–30 characters and contain only letters, numbers, underscores (_), or hyphens (-).",
    "INVALID_USERNAME_FORMAT": "Username can only contain letters, numbers, underscores (_), and hyphens (-).",
    "OUT_OF_RANGE": "Query out of range",
    "PASSWORDS_DO_NOT_MATCH": "Passwords do not match.",
    "REQUIRED": "This field is required.",
    "USERNAME_TOO_LONG": "Username must be no more than 30 characters.",
    "USERNAME_TOO_SHORT": "Username must be at least 3 characters."
  },
  "errors": {
    "AUTH_ACCOUNT_LOCKED": "Your account is temporarily locked. Try again later.",
    "AUTH_EMAIL_ALREADY_EXISTS": "This email already exists",
    "AUTH_EMAIL_NOT_VERIFIED": "Verify your email before signing in.",
    "AUTH_FORBIDDEN": "You do not have permission to access this resource.",
    "AUTH_INTERNAL_ERROR": "Something went wrong. Please try again.",
    "AUTH_INVALID_CREDENTIALS": "Invalid credentials",
    "AUTH_NO_PENDING_RECOVER": "No password reset request was found. Please start again.",
    "AUTH_RATE_LIMITED": "Too many attempts. Please try again later.",
    "AUTH_TOKEN_EXPIRED": "The verification link is invalid or expired.",
    "AUTH_UNAUTHORIZED": "You must be logged in to view this content.",
    "FETCH_FAILED": "API request failed. Try again later.",
    "FRIENDSHIP_ALREADY_ACCEPTED": "This request was already accepted.",
    "FRIENDSHIP_ALREADY_EXISTS": "You are already friends.",
    "FRIENDSHIP_NOT_FOUND": "Friendship not found.",
    "FRIENDSHIP_REQUEST_ALREADY_SENT": "A friend request has already been sent.",
    "FRIENDSHIP_REQUEST_NOT_FOUND": "Request not found or no longer available.",
    "FRIENDSHIP_SELF_REQUEST": "You cannot add yourself.",
    "generic": "Something went wrong. Please try again.",
    "INTERNAL_ERROR": "Something went wrong. Please try again.",
    "UNAUTHORIZED_ACTION": "Action not allowed.",
    "USER_NOT_FOUND": "User not found.",
    "VALIDATION_ERROR": "Validation error: please check the fields and try again."
  }
};
export default messages;