// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "navigation": {
    "home": "Home",
    "createAccount": "Create account",
    "login": "Log in",
    "UI": "UI",
    "robots": "Robots",
    "profile": "Profile",
    "logout": "Logout",
    "settings": "Settings"
  },
  "home": {
    "title": "Hello from Next in Docker 👋",
    "subtitle": "If you can see this, routing + dev server work."
  },
  "LocaleLayout": {
    "description": "This is an example of using next-intl in the `app` directory.",
    "title": "next-intl example"
  },
  "LocaleSwitcher": {
    "ariaLabel": "Language",
    "en": "EN",
    "es": "ES",
    "ca": "CA"
  },
  "TextAreaField": { "counter": "{current} of {max} characters" },
  "auth": {
    "common": {
      "appTitle": "Auth",
      "or": "OR",
      "identifier": {
        "label": "Email or username",
        "placeholder": "name@example.com or username",
        "description": "Use the email address or username you signed up with."
      },
      "email": {
        "label": "Email",
        "placeholder": "name@example.com"
      },
      "username": {
        "label": "Username",
        "placeholder": "your_username"
      },
      "password": {
        "label": "Password",
        "placeholder": "Enter your password",
        "description": "Min 8 characters long."
      },
      "confirmPassword": {
        "label": "Confirm password",
        "placeholder": "Re-enter your password"
      }
    },
    "login": {
      "title": "Log in",
      "submit": "Log in",
      "forgotPassword": "Forgot password?",
      "noAccount": "Don’t have an account?",
      "goToCreateAccount": "Create one",
      "withGoogle": "Continue with Google"
    },
    "createAccount": {
      "title": "Create account",
      "submit": "Create account",
      "haveAccount": "Already have an account?",
      "goToLogin": "Log in",
      "withGoogle": "Continue with Google",
      "success": {
        "title": "Check your email",
        "sent": "We've sent you an email to confirm your account.",
        "check": "Check your inbox and follow the instructions to activate your account.",
        "checkSpam": "If you can't find it, check your spam folder. If it's not there either, you can resend it.",
        "resend": "Resend email",
        "resending": "Sending...",
        "resent": "Email sent!",
        "resendSuccess": "✓ Email sent. Wait before trying again.",
        "resendError": "✗ Could not send email. Please try again.",
        "backToLogin": "Already confirmed? Sign in"
      }
    },
    "status": {
      "success": "Success",
      "error": "Something went wrong. Please try again."
    },
    "recover": {
      "title": "Recover account",
      "submit": "Send email",
      "resend": "Request another email",
      "goToLogin": "Go to log in"
    }
  },
  "api": {
    "AUTH_EMAIL_ALREADY_EXISTS": "This email already exists",
    "AUTH_INVALID_CREDENTIALS": "Invalid credentials"
  },
  "validation": {
    "REQUIRED": "This field is required.",
    "INVALID_EMAIL": "Enter a valid email address.",
    "INVALID_USERNAME": "Username must be 3–30 characters and contain only letters, numbers, underscores (_), or hyphens (-).",
    "INVALID_EMAIL_OR_USERNAME": "Enter a valid email address or username.",
    "INVALID_FORMAT": "Invalid format.",
    "USERNAME_TOO_SHORT": "Username must be at least 3 characters.",
    "USERNAME_TOO_LONG": "Username must be no more than 30 characters.",
    "INVALID_USERNAME_FORMAT": "Username can only contain letters, numbers, underscores (_), and hyphens (-).",
    "FIELD_TOO_SHORT": "Too short.",
    "FIELD_TOO_LONG": "Too long.",
    "PASSWORDS_DO_NOT_MATCH": "Passwords do not match.",
    "OUT_OF_RANGE": "Query out of range"
  },
  "Footer": {
    "appName": "Transcendence",
    "privacy": "Privacy Policy",
    "terms": "Terms of Service",
    "github": "GitHub",
    "copyright": "All rights reserved"
  },
  "settings": {
    "theme": "Theme",
    "language": "Language"
  }
};
export default messages;