"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VALIDATION_ERROR = exports.VALIDATION = void 0;
var status_1 = require("./status");
// ERRORS DETAILS THROW BY ZOD HERE
exports.VALIDATION = {
    REQUIRED: 'REQUIRED',
    INVALID_FORMAT: 'INVALID_FORMAT',
    FIELD_TOO_SHORT: 'FIELD_TOO_SHORT',
    FIELD_TOO_LONG: 'FIELD_TOO_LONG',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_USERNAME: 'INVALID_USERNAME',
    PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
    OUT_OF_RANGE: 'OUT_OF_RANGE',
    PASSWORD_MISSING_LETTER: 'PASSWORD_MISSING_LETTER',
    PASSWORD_MISSING_NUMBER: 'PASSWORD_MISSING_NUMBER',
};
// FORMAT GENERAL ERRORS
exports.VALIDATION_ERROR = {
    VALIDATION_ERROR: status_1.HttpStatus.UNPROCESSABLE_ENTITY,
};
//# sourceMappingURL=validation.js.map