export const FRIENDSHIPS_ERRORS = [
  "INTERNAL_ERROR",
  "VALIDATION_ERROR",
  "FRIENDSHIP_ALREADY_EXISTS",
  "FRIENDSHIP_REQUEST_NOT_FOUND",
  "FRIENDSHIP_ALREADY_ACCEPTED",
  "CANNOT_FRIEND_YOURSELF",
  "TARGET_USER_NOT_FOUND",
  "UNAUTHORIZED_ACTION",
] as const;

export type FriendshipsErrorName = (typeof FRIENDSHIPS_ERRORS)[number];

export const FRIENDSHIPS_ERROR_STATUS = {
  FRIENDSHIP_ALREADY_EXISTS: 409,
  FRIENDSHIP_REQUEST_NOT_FOUND: 404,
  FRIENDSHIP_ALREADY_ACCEPTED: 409,
  CANNOT_FRIEND_YOURSELF: 400,
  TARGET_USER_NOT_FOUND: 404,
  UNAUTHORIZED_ACTION: 403,
} as const;
