"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FRIENDSHIPS_ERROR_STATUS = exports.FRIENDSHIPS_ERRORS = void 0;
exports.FRIENDSHIPS_ERRORS = [
    'INTERNAL_ERROR',
    'VALIDATION_ERROR',
    'FRIENDSHIP_ALREADY_EXISTS',
    'FRIENDSHIP_REQUEST_NOT_FOUND',
    'FRIENDSHIP_NOT_FOUND',
    'FRIENDSHIP_ALREADY_ACCEPTED',
    'FRIENDSHIP_SELF_REQUEST',
    'FRIENDSHIP_REQUEST_ALREADY_SENT',
    'UNAUTHORIZED_ACTION',
];
exports.FRIENDSHIPS_ERROR_STATUS = {
    FRIENDSHIP_ALREADY_EXISTS: 409,
    FRIENDSHIP_REQUEST_NOT_FOUND: 404,
    FRIENDSHIP_NOT_FOUND: 404,
    FRIENDSHIP_ALREADY_ACCEPTED: 409,
    FRIENDSHIP_SELF_REQUEST: 422,
    FRIENDSHIP_REQUEST_ALREADY_SENT: 409,
    UNAUTHORIZED_ACTION: 403,
};
//# sourceMappingURL=friendships.errors.js.map