/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 alchemist.glb -T 
Files: alchemist.glb [15.92KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/alchemist-transformed.glb [2.04KB] (87%)
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function Alchemist(props) {
  const { nodes } = useGLTF('/models/alchemist-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.06, 0]} scale={[0.4, 0.4, 0.4]}>
        <Center>
          <mesh geometry={nodes.Cone001.geometry}>
            <meshStandardMaterial color="#22c55e" roughness={0.1} metalness={0.3} />
          </mesh>
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/alchemist-transformed.glb')
