/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assassin.glb -T 
Files: assassin.glb [9.66KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/assassin-transformed.glb [2.57KB] (73%)
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function Assassin(props) {
  const { nodes, materials } = useGLTF('/models/assassin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 4, -Math.PI / 4, 0]} scale={[0.35 * 1, 0.35 * 0.064, 0.35 * 0.249]}>
        <Center>
          <mesh geometry={nodes.Cube004.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.006']} />
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/assassin-transformed.glb')
