/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 crawler.glb -T 
Files: crawler.glb [38.5KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/crawler-transformed.glb [6.09KB] (84%)
*/

import React from 'react'
import { useGLTF, Center } from '@react-three/drei'

export function Crawler(props) {
  const { nodes, materials } = useGLTF('/models/crawler-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -0.209, 0]} scale={[0.5, 0.5, 0.5]}>
        <Center>
          <mesh geometry={nodes.Sphere_1.geometry} material={materials.Material} />
          <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sphere_3.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Sphere_4.geometry} material={materials['Material.003']} />
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/crawler-transformed.glb')
