/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 drone.glb -T 
Files: drone.glb [32.65KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/drone-transformed.glb [6.02KB] (82%)
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function Drone(props) {
  const { nodes, materials } = useGLTF('/models/drone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.0, 0.1, 0.0]} rotation={[0, -0.209, 0]} scale={[0.5, 0.5, 0.5]}>
        <Center>
          <mesh geometry={nodes.Sphere_1.geometry} material={materials.Material} />
          <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sphere_3.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Sphere_4.geometry} material={materials['Material.003']} />
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/drone-transformed.glb')
