/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fighter.glb -T 
Files: fighter.glb [26.99KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/fighter-transformed.glb [5.61KB] (79%)
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function Fighter(props) {
  const { nodes, materials } = useGLTF('/models/fighter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.27, 0]} rotation={[0, -0.209, 0]} scale={[0.4, 0.4, 0.4]}>
        <Center>
          <mesh geometry={nodes.Sphere_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Sphere_3.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Sphere_4.geometry} material={materials.Material} />
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/fighter-transformed.glb')
