/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Generator.glb -T 
Files: Generator.glb [4.31KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/Generator-transformed.glb [2.34KB] (46%)
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function Generator(props) {
  const { nodes, materials } = useGLTF('/models/Generator-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.04, 0]} scale={[0.35, 0.35, 0.35]}>
        <Center>
          <mesh geometry={nodes.Icosphere_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Icosphere_2.geometry} material={materials['Material.002']} />
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Generator-transformed.glb')
