/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gunner.glb -T 
Files: gunner.glb [39.03KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/gunner-transformed.glb [6.54KB] (83%)
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function Gunner(props) {
  const { nodes, materials } = useGLTF('/models/gunner-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.28, 0]} scale={[0.4, 0.4, 0.4]} rotation={[0, -0.209, 0]}>
        <Center>
          <mesh geometry={nodes.Sphere_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Sphere_3.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Sphere_4.geometry} material={materials.Material} />
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/gunner-transformed.glb')
