/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mage.glb -T 
Files: mage.glb [9.29KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/mage-transformed.glb [3KB] (68%)
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function Mage(props) {
  const { nodes, materials } = useGLTF('/models/mage-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.17, 0]} scale={[0.3, 0.3, 0.3]}>
        <Center>
          <mesh geometry={nodes.Cone_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cone_2.geometry} material={materials['Material.002']} />
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mage-transformed.glb')
