/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 paladin.glb -T 
Files: paladin.glb [17.81KB] > /Users/crismac/transcendence/containers/frontend/web/src/features/game/paladin-transformed.glb [3.1KB] (83%)
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function Paladin(props) {
  const { nodes, materials } = useGLTF('/models/paladin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.025, 0]} scale={[-0.35, 0.35, -0.35]}>
        <Center>
          <mesh geometry={nodes.Cube002.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.006']} />
        </Center>
      </group>
    </group>
  )
}

useGLTF.preload('/models/paladin-transformed.glb')
