// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "navigation": {
    "home": "Home",
    "signup": "Sign up",
    "login": "Log in"
  },
  "auth": {
    "signup": {
      "title": "Create account",
      "email": "Email address",
      "password": "Password",
      "submit": "Create account"
    }
  },
  "home": {
    "title": "Hello from Next in Docker 👋",
    "subtitle": "If you can see this, routing + dev server work."
  },
  "LocaleLayout": {
    "description": "This is an example of using next-intl in the `app` directory.",
    "title": "next-intl example"
  },
  "Navigation": {
    "about": "About (MDX)",
    "client": "Client page",
    "home": "Home",
    "nested": "Nested page",
    "newsArticle": "News article #{articleId}"
  },
  "LocaleSwitcher": {
    "switchLocale": "Change to {locale, select, es {Spanish} en {English} other {Unknown}}"
  }
};
export default messages;