// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "navigation": {
    "home": "Inicio",
    "signup": "Registrarse",
    "login": "Iniciar sesión"
  },
  "auth": {
    "signup": {
      "title": "Crear cuenta",
      "email": "Correo electrónico",
      "password": "Contraseña",
      "submit": "Crear cuenta"
    }
  },
  "home": {
    "title": "Hola desde Next en Docker 👋",
    "subtitle": "Si ves esto, el routing y el servidor de desarrollo funcionan."
  },
  "LocaleLayout": {
    "description": "Este es un ejemplo de cómo usar next-intl en el directorio app.",
    "title": "Ejemplo next-intl"
  },
  "Navigation": {
    "about": "Acerca de (MDX)",
    "client": "Página del cliente",
    "home": "Inicio",
    "nested": "Página anidada",
    "newsArticle": "Noticias #{articleId}"
  },
  "LocaleSwitcher": {
    "switchLocale": "Cambiar a {locale, select, de {Alemán} en {Inglés} other {Desconocido}}"
  }
};
export default messages;