import { HttpStatus } from '../http/status';

export const GAME_INVITATIONS_ERROR_STATUS = {
  GAME_INVITATION_ALREADY_IN_ROOM: HttpStatus.CONFLICT,
  GAME_INVITATION_ALREADY_ACCEPTED: HttpStatus.CONFLICT,
  GAME_INVITATION_ALREADY_CANCELLED: HttpStatus.CONFLICT,
  GAME_INVITATION_DUPLICATE_PENDING: HttpStatus.CONFLICT,
  GAME_INVITATION_EXPIRED: HttpStatus.CONFLICT,
  GAME_INVITATION_NOT_FOUND: HttpStatus.NOT_FOUND,
  GAME_INVITATION_NOT_JOINABLE: HttpStatus.CONFLICT,
  GAME_INVITATION_NOT_FRIEND: HttpStatus.FORBIDDEN,
  GAME_INVITATION_PENDING_LIMIT: HttpStatus.TOO_MANY_REQUESTS,
  GAME_INVITATION_RATE_LIMITED: HttpStatus.TOO_MANY_REQUESTS,
  GAME_INVITATION_RECENT_DUPLICATE: HttpStatus.TOO_MANY_REQUESTS,
  GAME_INVITATION_ROOM_REQUIRED: HttpStatus.CONFLICT,
  GAME_INVITATION_ROOM_UNAVAILABLE: HttpStatus.CONFLICT,
} as const;

export type GameInvitationsErrorName = keyof typeof GAME_INVITATIONS_ERROR_STATUS;
