import type { Meta, StoryObj } from '@storybook/nextjs-vite';

import { Breadcrumb } from './breadcrumb';

const meta = {
  title: 'Components/Composites/Breadcrumb',
  component: Breadcrumb,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Breadcrumb navigation component. It can receive explicit items or auto-generate them from the current pathname.',
      },
    },
  },
  argTypes: {
    items: {
      control: 'object',
      description:
        'Optional list of breadcrumb items. When provided, these items are rendered instead of generating breadcrumbs from the current pathname.',
      table: {
        category: 'Content',
        type: {
          summary: '{ label: string; href: string }[]',
        },
      },
    },
    hideHome: {
      control: 'boolean',
      description: 'Removes the home breadcrumb item from the generated breadcrumb list.',
      table: {
        category: 'Behavior',
        type: {
          summary: 'boolean',
        },
        defaultValue: {
          summary: 'false',
        },
      },
    },
  },
  args: {
    hideHome: false,
    items: [
      {
        label: 'Home',
        href: '/',
      },
      {
        label: 'Profile',
        href: '/me',
      },
      {
        label: 'Settings',
        href: '/me/reset-password',
      },
    ],
  },
} satisfies Meta<typeof Breadcrumb>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const SingleItem: Story = {
  args: {
    items: [
      {
        label: 'Home',
        href: '/',
      },
    ],
  },
};

export const HideHome: Story = {
  args: {
    hideHome: true,
    items: [
      {
        label: 'Profile',
        href: '/me',
      },
      {
        label: 'Settings',
        href: '/me/reset-password',
      },
    ],
  },
};

export const AutoGeneratedFromPathname: Story = {
  args: {
    items: undefined,
    hideHome: false,
  },
  parameters: {
    nextjs: {
      appDirectory: true,
      navigation: {
        pathname: '/me/reset-password',
      },
    },
    docs: {
      source: {
        code: `<Breadcrumb />`,
      },
    },
  },
};
